id: P83B4562F
initial_creation_type: input
source_metadata:
  title: Gītārthasaṃgraha
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy -- Vedānta
  data entry: Sadanori Ishitobi
  contribution to GRETIL: Sadanori Ishitobi
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T14:57:46.224655'
last_modified_at: '2022-03-09T14:57:46.224679'
